site :opscode

cookbook 'apt'
cookbook 'git'
cookbook 'nginx'
cookbook 'mongodb'
cookbook 'postgresql'
cookbook 'openfire'
cookbook 'jaffa', path: 'cookbooks/jaffa'
cookbook 'jaffa_openfire', path: 'cookbooks/jaffa_openfire'
